/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        h1: ["Manrope"],
        "mono-telemetry": ["monospace"],
        "label-sm": ["Inter"],
        h2: ["Manrope"],
        "mono-data": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "hero-headline": ["Manrope"],
        h3: ["Manrope"],
      },
      colors: {
        royalpurple: '#6A0DAD',
        black: '#000000',
        white: '#FFFFFF',
        "outline-variant": "#E0E0E0",
        "surface": "#FFFFFF",
        "surface-container-highest": "#F5F5F5",
        "accent-lime": "#A4D433",
        "inverse-primary": "#3d4ae0",
        "error": "#BA1A1A",
        "primary": "#1F2BC8",
        "surface-container-lowest": "#FFFFFF",
        "outline": "#757780",
        "on-primary": "#FFFFFF",
        "surface-variant": "#F1F1F4",
        "surface-container": "#F8F9FA",
        "text-muted": "#64748B",
        "surface-dim": "#F1F1F2",
        "on-secondary": "#FFFFFF",
        "on-surface-variant": "#45464F",
        "background": "#FFFFFF",
        "divider-subtle": "#E2E8F0",
        "background-deep": "#F8FAFC",
        "accent-cyan-soft": "#006874",
        "surface-panel": "#FFFFFF",
        "on-surface": "#1A1C1E",
        "primary-container": "#E0E0FF",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      spacing: {
        "lg": "24px",
        "xs": "4px",
        "xl": "40px",
        "sm": "8px",
        "md": "20px",
        "base": "16px",
        "margin-safe": "32px",
        "gutter": "20px",
      },
      fontSize: {
        "h1": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.05em", "fontWeight": "520" }],
        "mono-telemetry": ["9px", { "lineHeight": "1.2", "letterSpacing": "0.2em", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "h2": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.05em", "fontWeight": "520" }],
        "mono-data": ["13px", { "lineHeight": "1.0", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "body-lg": ["19px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "hero-headline": ["76px", { "lineHeight": "1.1", "letterSpacing": "-0.055em", "fontWeight": "520" }],
        "h3": ["24px", { "lineHeight": "1.2", "letterSpacing": "-0.04em", "fontWeight": "520" }],
      },
    },
  },
  plugins: [],
};
